# Generated by Django 5.1.6 on 2025-02-27 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='execution_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buy_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_bought', to='trading.order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sell_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_sold', to='trading.order'),
        ),
    ]
