# Generated by Django 5.2 on 2025-04-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume_used',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
